apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-media-pvc
  namespace: bapies-media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi 
  storageClassName: openebs-localpv-drive1
